### PR TITLE
Feature/purplescenariocolor

### PR DESCRIPTION
**Pull request by shami-sneha**
### Checklist

**I, the author of this PR checked the following requirements for good software quality:**

- [x] The code is properly formatted (I ran the formatter)
- [x] The code is written with our software quality standards (I ran the linter)
- [x] The code is written using our code style
- [x] Extensive in source documentation has been added
- [x] Unit and/or integration tests have been added
- [x] All texts have been internationalized with at least the following languages:
  - [x] English
  - [ ] German
- [x] I tried addressing all new accessibility problems displayed in the console and documented if they can't be fixed
- [x] I attached performance measurements to prevent performance degradation
- [x] I added the changes to the next release section of the [changelog](../frontend/docs/changelog/changelog-en.md)

**I, the reviewer checked the following things:**

- [ ] I ran the software once and tried all new and related functionality to this PR
- [ ] I looked at all new and changed lines of code and commented on possible problems
- [ ] I read the added documentation and checked if it is understandable and clear
- [ ] I checked the added tests for completeness
- [ ] I checked the internationalized strings for spelling errors
- [ ] I checked the performance metrics for problems or unexplained degradation
- [ ] I checked that the changes are noted in the [changelog](../frontend/docs/changelog/changelog-en.md)

### CODE REVIEW

**Comment by JonasGilg** [comment]
Hi, what is this pull request about? Can you fill out the template please?

**Comment by shami-sneha** [comment]
sorry for that  let me check ....

**Comment by JonasGilg** [comment]
Can you also please fill out the description and related issue part of the template? Additionally I saw, that you changed 33 files, from which not all seem related to theis PR.

**Comment by shami-sneha** [comment]
Hey jonas,

Yes, I will fix that. But need your help to solve this. Last time, I had
some issues when i was merging. Friday I will come to  office and we can
sit together,  solve the issue. Is that okay?

Thank you
Regard
Shami Snehlata

**Pull request closed without merging**
