### PR TITLE
Fix site crash when scenario was deleted from DB

### PR DESCRIPTION
**Pull request by JonasGilg**
### Description

Fixes an issue with the persistent store when a scenario is deleted from the database (scenario ID returns 500 on API fetch).
This issue ocurrs when the redux store still has the scenario id cached in the `activeScenarios` and `scenarioList` and the Simulation Chart or Data Cards try to fetch data with this scenario id from the API.
To fix this, IDs in the `activeScenarios` are ignored if the ID is not in the `sceanrioList`.
Additionally the `scenarioList` is not persisted and fetched newly on every load.

### Checklist

**I, the author of this PR checked the following requirements for good software quality:**

- [x] The code is properly formatted (I ran the formatter)
- [x] The code is written with our software quality standards (I ran the linter)
- [x] The code is written using our code style
- [x] Extensive in source documentation has been added
- [ ] ~Unit and/or integration tests have been added~
- [x] All texts have been internationalized with at least the following languages:
  - [x] English
  - [x] German
- [x] I tried addressing all new accessibility problems displayed in the console and documented if they can't be fixed
- [ ] ~I attached performance measurements to prevent performance degradation~
- [x] I added the changes to the next release section of the [changelog](../frontend/docs/changelog/changelog-en.md)

**I, the reviewer checked the following things:**

- [ ] I ran the software once and tried all new and related functionality to this PR
- [ ] I looked at all new and changed lines of code and commented on possible problems
- [ ] I read the added documentation and checked if it is understandable and clear
- [ ] I checked the added tests for completeness
- [ ] I checked the internationalized strings for spelling errors
- [ ] I checked the performance metrics for problems or unexplained degradation
- [ ] I checked that the changes are noted in the [changelog](../frontend/docs/changelog/changelog-en.md)

### CODE REVIEW

**Comment by NXXR** [comment]
@annawendler can you checkout this branch and see if it fixes your issue with the updating scenario?

**Comment by annawendler** [comment]
I still have the issue, when I update the scenario I get the error message "Uncaught TypeError: theme.custom.scenarios[props.scenario.id] is undefined".

**Comment by JonasGilg** [comment]
> I still have the issue, when I update the scenario I get the error message "Uncaught TypeError: theme.custom.scenarios[props.scenario.id] is undefined".

Can you try again?

**Comment by annawendler** [comment]
Now the display works after updating the scenario without clearing the cache. However, when I click on the scenario to view the uncertainties the site goes blank. If I remember correctly this worked before but I'm not sure or if this is a different issue.
image

**Comment by annawendler** [comment]
It's working now! The only thing is that now the colors of the uncertainties aren't matching with the line of the scenario anymore.
image

**Comment by JonasGilg** [comment]
> It's working now! The only thing is that now the colors of the uncertainties aren't matching with the line of the scenario anymore. image

This should be fixed as well. We will rework how scenarios are colored in the future, since we currently assume that the scenarios have rising ids starting from 1. See #330.

**Comment by annawendler** [comment]
It is fixed now.

**Review by NXXR — DISMISSED** [review]

**Review by NXXR — APPROVED** [review]

**Pull request merged**
