### PR TITLE
:wrench: Implement baseline scenario day selection for initial scenar…

### PR DESCRIPTION
**Pull request by hudaif747**
…io list

### Description
On initial load we had only case data card activated by default. Made changes to also activate the first scenario card (assuming it to be baseline scenario). The initial date would be the end date available for the particular scenario. Also added startDate and endDate calculating function in DataCardList component for reusability.

#### Related Issues

#364 

### Design Decisions
-

### Performance & Quality
-

### Checklist

**I, the author of this PR checked the following requirements for good software quality:**

- [x] The code is properly formatted (I ran the formatter)
- [x] The code is written with our software quality standards (I ran the linter)
- [x] The code is written using our code style
- [ ] Extensive in source documentation has been added
- [x] Unit and/or integration tests have been added
- [ ] All texts have been internationalized with at least the following languages:
  - [ ] English
  - [ ] German
- [x] I tried addressing all new accessibility problems displayed in the console and documented if they can't be fixed
- [ ] I attached performance measurements to prevent performance degradation
- [ ] I added the changes to the next release section of the [changelog](../frontend/docs/changelog/changelog-en.md)

**I, the reviewer checked the following things:**

- [ ] I ran the software once and tried all new and related functionality to this PR
- [ ] I looked at all new and changed lines of code and commented on possible problems
- [ ] I read the added documentation and checked if it is understandable and clear
- [ ] I checked the added tests for completeness
- [ ] I checked the internationalized strings for spelling errors
- [ ] I checked the performance metrics for problems or unexplained degradation
- [ ] I checked that the changes are noted in the [changelog](../frontend/docs/changelog/changelog-en.md)

### CODE REVIEW

**Review by JonasGilg — CHANGES_REQUESTED** [review]
Thank you very much, for a first time visitor this already works as inteded. This sadly interferes with the persistence, since the state for revisiting users gets overridden each time.

Can you try to prefer the state from the store and only do this when a user visits ESID for the first time?

**Comment by hudaif747** [comment]
@JonasGilg My bad. I completely overlooked the persistance part. 

Is it okay to set the activeScenarios directly in the DataSelectionSlice initial setting (activeScenarios: [0,1])?
Also, can we track the user visit using a boolean flag called "userVisited"?

**Comment by JonasGilg** [comment]
> @JonasGilg My bad. I completely overlooked the persistance part.
> 
> Is it okay to set the activeScenarios directly in the DataSelectionSlice initial setting (activeScenarios: [0,1])? Also, can we track the user visit in the store using a boolean flag called "userVisited" to keep track of the users initial visit?

Yes, both should be possible. As long as it works. I don't see a problem with this solution. Just be sure, that the site doesn't break if for some reason no scenario is available.

**Comment by hudaif747** [comment]
@JonasGilg I've implemented your suggestions. I added a userVisited flag in the UserPreference slice to track initial user visits. The baseline scenario card is now initialized by default in activeScenarios in the DataSelection slice. The useEffect in DataCardList component selects the baseline scenario if available. I reverted earlier changes to the DataCardList component as they are not required anymore.

Do you have any suggestions for checking the user's initial visit without using the redux store? I tried a few approaches but couldn't find a suitable solution other than this.

**Review by JonasGilg — APPROVED** [review]

**Comment by hudaif747** [comment]
@JonasGilg I had some issues with merging this Pull Request as it was stale after the update of the application to use VVAFER components. I ran into some trouble while merging with the develop with the stale PR. I have made the changes now could you please go through it and review the changes?

**Review by JonasGilg — APPROVED** [review]

**Comment by JonasGilg** [comment]
> @JonasGilg I've implemented your suggestions. I added a userVisited flag in the UserPreference slice to track initial user visits. The baseline scenario card is now initialized by default in activeScenarios in the DataSelection slice. The useEffect in DataCardList component selects the baseline scenario if available. I reverted earlier changes to the DataCardList component as they are not required anymore.
> 
> Do you have any suggestions for checking the user's initial visit without using the redux store? I tried a few approaches but couldn't find a suitable solution other than this.

The implementation with the redux store is good. It is easily reusable for other components, if needed.

**Pull request merged**
