### PR TITLE
Change api routes to accept filter request via get and post

### PR DESCRIPTION
**Pull request by lucaspataro**

### CODE REVIEW

**Review by NXXR — APPROVED** [review]

**Comment by NXXR** [comment]
@lucaspataro @JonasGilg can one of you two do a quick review of the frontend changes I added to make sure everything is in order?

**Review by NXXR — DISMISSED** [review]

**Review by JonasGilg — DISMISSED** [review]
I approve these changes. The merge to develop and the internal deploy should happen at once, so develop is always in a working state with our internally deployed backend.

**Comment by JonasGilg** [comment]
> I have to add something, before we merge. The percentiles aren't shown anymore. Is this known?

It looks like p25, p50 and p75 have always the same values.

**Comment by lucaspataro** [comment]
Yes you are right! Good catch, i will fix it.

**Review by NXXR — APPROVED** [review]

**Comment by JonasGilg** [comment]
Is there a reason, that this is approved, but not merged yet?

**Comment by lucaspataro** [comment]
Yes! While working with the changes, Kerem found a situation where no data was send back to the client. I investigated a little and think there should have been data, so i have to take a deeper look into that next week.

**Pull request merged**
